"""empty message

Revision ID: 053d3730f9c5
Revises: f818b25aa254
Create Date: 2021-12-04 10:44:39.644408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053d3730f9c5'
down_revision = 'f818b25aa254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('test_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
