"""empty message

Revision ID: 303413439953
Revises: 28f75bea772d
Create Date: 2021-12-04 16:13:40.232739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303413439953'
down_revision = '28f75bea772d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('familiar')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('familiarity_level', sa.VARCHAR(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('familiar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=70), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=70), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=70), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=6), nullable=True),
    sa.Column('birth_date', sa.DATETIME(), nullable=True),
    sa.Column('hobby', sa.VARCHAR(length=70), nullable=True),
    sa.Column('category_familiar_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_familiar_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
