"""empty message

Revision ID: 2b9c47972515
Revises: 303413439953
Create Date: 2021-12-04 16:14:47.762331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9c47972515'
down_revision = '303413439953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familiarity_level', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('familiar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=70), nullable=False),
    sa.Column('first_name', sa.String(length=70), nullable=False),
    sa.Column('phone_number', sa.String(length=70), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True),
    sa.Column('birth_date', sa.String(length=70), nullable=True),
    sa.Column('hobby', sa.String(length=70), nullable=True),
    sa.Column('category_familiar_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_familiar_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('familiar')
    op.drop_table('category')
    # ### end Alembic commands ###
